# Generated by Django 4.0.5 on 2022-06-19 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_age'),
        ('ads', '0002_remove_ads_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
