# Generated by Django 4.0.5 on 2022-06-19 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_location_lat_location_lng'),
        ('ads', '0003_alter_ads_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='author_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
